### ISSUE TITLE
modellen belüli elnevezések

### ISSUE THREAD

**Issue by Breinich** [ftsrg-rete/rete-lecture-notes#2]
Ez inkább a Papyrussal, mint a tutoriallal kapcsolatos issue

-**Ő vagy ő** betű esetén g-t jelenít meg a diagram nézet, illetve
-Ha tartalmazza a szó azt, hogy **fi**, akkor az **fi** helyett egy gondolatjel látszódik

**Comment by Rorck** [comment]
Tudnál küldeni egy példa modellt? Én most gyorsan kipróbáltam, nekem rendesen jelennek meg a karakterek.

**Comment by Breinich** [comment]
> Tudnál küldeni egy példa modellt?

lehet valami betűtípus beállítás lesz a probléma, nekem a relációs jelek helyett pedig integrál jelet mutat
![image](https://user-images.githubusercontent.com/74102716/191080133-8cd99007-c91d-4a78-80fa-cbd27c4c106b.png)

**Comment by Rorck** [comment]
Ez szinte biztosan valamilyen encoding probléma lesz, a papyrus vagy az os oldalán, ezeket kéne megnézni, hogy mindenhol UTF-8 legyen.

**Comment by Breinich** [comment]
Rendben, megpróbálom.

**Comment by Breinich** [comment]
Megoldódott a probléma. Az OS betűtípusát kellett visszaállítsam, mivel régebben egyedire átállítottam, aztán én ittam meg a levét.
